#!/usr/bin/env bun
import { readdirSync, statSync, readFileSync, writeFileSync } from "fs";
import { join } from "path";
import { z } from "zod";
import { tempo } from "@joggr/tempo";

const tokenSchema = z.union([z.string(), z.array(z.string())]);

const paginatorsFileSchema = z.object({
  pagination: z.record(
    z.string(),
    z.object({
      input_token: tokenSchema.optional(),
      output_token: tokenSchema.optional(),
      limit_key: z.string().optional(),
      result_key: z.union([z.string(), z.array(z.string())]).optional(),
      more_results: z.string().optional(),
    })
  ),
});

console.log("Starting AWS SDK paginator check...");
console.log("AWS SDK repository location: ./aws-sdk-java-v2");

function findPaginatorFiles(dir: string, results: string[] = []): string[] {
  try {
    const files = readdirSync(dir);

    for (const file of files) {
      const filePath = join(dir, file);

      try {
        const stat = statSync(filePath);

        if (stat.isDirectory()) {
          findPaginatorFiles(filePath, results);
        } else if (file === "paginators-1.json") {
          results.push(filePath);
        }
      } catch {
        continue;
      }
    }
  } catch {
    // ignore unreadable dirs
  }

  return results;
}

function extractServiceName(path: string): string {
  const parts = path.split("/");
  const servicesIndex = parts.indexOf("services");

  if (servicesIndex !== -1 && servicesIndex + 1 < parts.length) {
    return parts[servicesIndex + 1];
  }

  return path;
}

function createGitHubLink(paginatorFilePath: string): string {
  const relativePath = paginatorFilePath.replace("aws-sdk-java-v2/", "");
  const githubBaseUrl = "https://github.com/aws/aws-sdk-java-v2/blob/master";
  return `${githubBaseUrl}/${relativePath}`;
}

function normalizeToken(token: string | string[] | undefined): string {
  if (token === undefined) return "";
  if (Array.isArray(token)) return token.join(", ");
  return token;
}

const allPaginatorFiles = findPaginatorFiles("./aws-sdk-java-v2");

const paginatorFiles = allPaginatorFiles.filter(
  (path) => !path.includes("/test/") && !path.includes("/codegen/")
);

console.log(
  `\nFound ${paginatorFiles.length} paginators-1.json files (excluding tests)\n`
);

console.log("Services with paginators:");

const tableData: Array<Array<string | ((text: any) => any)>> = [
  ["Service", "Operation", "Input Token", "Output Token"],
];

const paginatorRows: Array<{
  serviceName: string;
  githubUrl: string;
  operationName: string;
  inputToken: string;
  outputToken: string;
}> = [];

for (const paginatorFile of paginatorFiles) {
  const serviceName = extractServiceName(paginatorFile);
  const githubUrl = createGitHubLink(paginatorFile);

  try {
    const content = readFileSync(paginatorFile, "utf-8");
    const json = JSON.parse(content);
    const validated = paginatorsFileSchema.parse(json);

    console.log(`\n${serviceName}:`);

    for (const [operationName, paginator] of Object.entries(
      validated.pagination
    )) {
      const inputToken = normalizeToken(paginator.input_token);
      const outputToken = normalizeToken(paginator.output_token);

      console.log(`  - ${operationName}`);
      console.log(`    Input token:  ${inputToken || "(none)"}`);
      console.log(`    Output token: ${outputToken || "(none)"}`);

      paginatorRows.push({
        serviceName,
        githubUrl,
        operationName,
        inputToken,
        outputToken,
      });
    }
  } catch (err) {
    console.error(`\nError processing ${serviceName}:`, err);
  }
}

paginatorRows.sort((a, b) => {
  const serviceCompare = a.serviceName.localeCompare(b.serviceName);
  if (serviceCompare !== 0) return serviceCompare;
  return a.operationName.localeCompare(b.operationName);
});

for (const row of paginatorRows) {
  tableData.push([
    (text) => text.link(row.serviceName, row.githubUrl),
    row.operationName,
    row.inputToken,
    row.outputToken,
  ]);
}

const readme = tempo()
  .h1("AWS SDK Paginators")
  .paragraph(
    "The following table contains all known paginators in the AWS SDKs. This README is automatically generated by GitHub Actions."
  )
  .table(tableData)
  .toString();

writeFileSync("README.md", readme, "utf-8");

console.log("\nScript completed successfully!");
console.log(
  `Generated README.md with ${tableData.length - 1} paginators from ${paginatorFiles.length} services`
);
